theme: jekyll-theme-minimal
title: OAuth2 Spring server working template
description: Ready to use OAuth2 Spring Boot server for usage in real projects or for learning purposes!

kramdown:
  parse_block_html: true
  auto_ids: true